steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t', 'gcr.io/$PROJECT_ID/grocery-backend',
        '-f', 'app/backend/Dockerfile',
        '.'
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/grocery-backend']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run', 'deploy', 'grocery-backend',
        '--image', 'gcr.io/$PROJECT_ID/grocery-backend',
        '--region', 'asia-south1',
        '--platform', 'managed',
        '--allow-unauthenticated',
        '--port', '8080'
      ]

images:
  - 'gcr.io/$PROJECT_ID/grocery-backend'

options:
  logging: CLOUD_LOGGING_ONLY
